#!/bin/bash
#IP=$(sed -n 's/.*\(\(\(^\| \)[0-9]\{1,3\}\.\)\{1\}\([0-9]\{1,3\}\.\)\{2\}[0-9]\{1,3\}\) .*/\1/gp' ./nginx.log) 
#echo $IP
echo "ip "
grep -Eo '^([0-9]{1,3}\.){3}[0-9]{1,3}' ./nginx.log | uniq -cd | sort -n | tail | sort -r
grep -o '[A-Za-z0-9]*\.php' ./nginx.log > ./url
grep -o '[A-Za-z0-9]*\.html' ./nginx.log >> ./url
echo "url "
sort ./url | uniq -cd | sort -nr | head

